Homework1 Ivan Veremeichik
belovmd/it-academy-winter-2021 pull request #3
Opened 2021-11-19 17:48 UTC by NorgeMan

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-11-28 19:56 UTC, belovmd requested changes

2021-11-28 19:56 UTC, belovmd commented on src/homework1.py
> +greet('Jack')
you have 2 lines between a function definition and it's call and you have only one line between It and next task. I suggest such pattern:

```python
   pass  # last line of previous task
    
 
   # next task docstring
   pass  # my next task first line  
```

2021-11-28 19:56 UTC, belovmd commented on src/homework1.py
> +
usually, you have 0 lines between docstring and code and here you have 1 empty line between it. you code should be consistent.

2021-11-28 19:56 UTC, belovmd commented on src/homework1.py
> +
same issue

2021-11-29 20:51 UTC, NorgeMan reviewed
code was fixed after review

2021-12-12 18:16 UTC, belovmd approved these changes
1

2021-12-12 18:16 UTC, closed without merging