Homework1: Andrey Sokolovsky
belovmd/it-academy-winter-2021 pull request #8
Opened 2021-11-20 10:18 UTC by 4sokky

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-11-28 20:02 UTC, belovmd requested changes

2021-11-28 20:02 UTC, belovmd commented on src/homework1/simple_prog10.py
> +bottles_of_beer = 9
it has sense to split constant and code with 1 empty line

2021-11-28 20:02 UTC, belovmd commented on src/homework1/simple_prog12.py
> +
here you have imports and code splitted with 2 blank lines.

2021-11-28 20:02 UTC, belovmd commented on src/homework1/simple_prog14.py
> +from itertools import groupby
here you have imports and code splitted with 0 blank lines. it should be consistent

2021-11-28 20:02 UTC, belovmd commented on src/homework1/simple_prog14.py
> +# PRINTS:
redundant comment

2021-11-28 20:02 UTC, belovmd commented on src/homework1/simple_prog16.py
> +
here is constant is separated with 2 blank lines (earlier you had 0 line split in task 10 and task14

2021-11-28 20:02 UTC, belovmd commented on src/homework1/simple_prog9.py
> +
1 line between import and code

2021-11-29 16:54 UTC, 4sokky commented on src/homework1/simple_prog10.py
> +bottles_of_beer = 9
if i understand correctly, i should split constant same like imports, so with 2 blank lines after them (for the consistency). right?

2021-12-12 18:19 UTC, belovmd approved these changes
1

2021-12-12 18:19 UTC, closed without merging